### ISSUE TITLE
problems in installation with composer

### ISSUE THREAD

**Issue by hdkcreative** [nikosid/yii2-cloudinary#1]
```
php composer.phar require nikosid/yii2-cloudinary "dev-master"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nikosid/yii2-cloudinary dev-master -> satisfiable by nikosid/yii2-cloudinary[dev-master].
    - nikosid/yii2-cloudinary dev-master requires cloudinary/cloudinary_php dev-master -> satisfiable by cloudinary/cloudinary_php[dev-master] but these conflict with your requirements or minimum-stability.
```

**Comment by hdkcreative** [comment]
we install package by package... and all is ok ...

but when try to use:

**error : CloudinaryBehavior ... not found ..**

we  add:

```
use nikosid\yii2-cloudinary\CloudinaryBehavior

or use nikosid\yii2-cloudinary\cloudinary;
```


**and this not work...yhe same message: error : CloudinaryBehavior ... not found ..**


any solution ?

[https://preview.ibb.co/n4RCMU/Screen_Shot_2018_08_08_at_7_11_40_PM.png](https://preview.ibb.co/n4RCMU/Screen_Shot_2018_08_08_at_7_11_40_PM.png)

**Comment by nikosid** [comment]
@hdkcreative, what is minimum-stability level on your project?
And when you get this error not fount?
I've just tested it - downloaded yii2-basic, then installed this library by `php composer.phar require nikosid/yii2-cloudinary "dev-master"` and it works.
I've corrected README.md a little, maybe it help with your error

**Comment by hdkcreative** [comment]
hi @nikosid thank you for you response...

we get this error on  2018 08 08 at 7:11: PM

**what is minimum-stability level on your project?**
we are in the initial phase of our proyect

we install the library directly from cloudinary.. .and all fine ! .. work... but we want use you widget
